# Generated by Django 3.2.4 on 2021-10-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Инфорамция о нас')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Инфорамция о портфолио')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_project', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя проекта')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='static/img/website/projects')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('service_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Инфорамция о услуге')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('speciality', models.CharField(blank=True, max_length=128, null=True, verbose_name='Специальность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/adminpanel/img/team')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя заказчика')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.country')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.status')),
            ],
        ),
    ]
